/*
 * This file is generated by jOOQ.
*/
package org.mrc.ide.auth.db;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.mrc.ide.auth.db.tables.AppUser;
import org.mrc.ide.auth.db.tables.Permission;
import org.mrc.ide.auth.db.tables.Role;
import org.mrc.ide.auth.db.tables.RolePermission;
import org.mrc.ide.auth.db.tables.UserGroup;
import org.mrc.ide.auth.db.tables.UserGroupMembership;
import org.mrc.ide.auth.db.tables.UserGroupRole;
import org.mrc.ide.auth.db.tables.records.AppUserRecord;
import org.mrc.ide.auth.db.tables.records.PermissionRecord;
import org.mrc.ide.auth.db.tables.records.RolePermissionRecord;
import org.mrc.ide.auth.db.tables.records.RoleRecord;
import org.mrc.ide.auth.db.tables.records.UserGroupMembershipRecord;
import org.mrc.ide.auth.db.tables.records.UserGroupRecord;
import org.mrc.ide.auth.db.tables.records.UserGroupRoleRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RoleRecord, Integer> IDENTITY_ROLE = Identities0.IDENTITY_ROLE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppUserRecord> APP_USER_PKEY = UniqueKeys0.APP_USER_PKEY;
    public static final UniqueKey<PermissionRecord> PERMISSION_PKEY = UniqueKeys0.PERMISSION_PKEY;
    public static final UniqueKey<RoleRecord> ROLE_PKEY = UniqueKeys0.ROLE_PKEY;
    public static final UniqueKey<RolePermissionRecord> ROLE_PERMISSION_PKEY = UniqueKeys0.ROLE_PERMISSION_PKEY;
    public static final UniqueKey<UserGroupRecord> USER_GROUP_PKEY = UniqueKeys0.USER_GROUP_PKEY;
    public static final UniqueKey<UserGroupMembershipRecord> USER_GROUP_MEMBERSHIP_PKEY = UniqueKeys0.USER_GROUP_MEMBERSHIP_PKEY;
    public static final UniqueKey<UserGroupRoleRecord> USER_GROUP_ROLE_PKEY = UniqueKeys0.USER_GROUP_ROLE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserGroupMembershipRecord, AppUserRecord> USER_GROUP_MEMBERSHIP__USER_GROUP_MEMBERSHIP_USERNAME_FKEY = ForeignKeys0.USER_GROUP_MEMBERSHIP__USER_GROUP_MEMBERSHIP_USERNAME_FKEY;
    public static final ForeignKey<UserGroupMembershipRecord, UserGroupRecord> USER_GROUP_MEMBERSHIP__USER_GROUP_MEMBERSHIP_USER_GROUP_FKEY = ForeignKeys0.USER_GROUP_MEMBERSHIP__USER_GROUP_MEMBERSHIP_USER_GROUP_FKEY;
    public static final ForeignKey<UserGroupRoleRecord, UserGroupRecord> USER_GROUP_ROLE__USER_GROUP_ROLE_USER_GROUP_FKEY = ForeignKeys0.USER_GROUP_ROLE__USER_GROUP_ROLE_USER_GROUP_FKEY;
    public static final ForeignKey<UserGroupRoleRecord, RoleRecord> USER_GROUP_ROLE__USER_GROUP_ROLE_ROLE_FKEY = ForeignKeys0.USER_GROUP_ROLE__USER_GROUP_ROLE_ROLE_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RoleRecord, Integer> IDENTITY_ROLE = Internal.createIdentity(Role.ROLE, Role.ROLE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AppUserRecord> APP_USER_PKEY = Internal.createUniqueKey(AppUser.APP_USER, "app_user_pkey", AppUser.APP_USER.USERNAME);
        public static final UniqueKey<PermissionRecord> PERMISSION_PKEY = Internal.createUniqueKey(Permission.PERMISSION, "permission_pkey", Permission.PERMISSION.NAME);
        public static final UniqueKey<RoleRecord> ROLE_PKEY = Internal.createUniqueKey(Role.ROLE, "role_pkey", Role.ROLE.ID);
        public static final UniqueKey<RolePermissionRecord> ROLE_PERMISSION_PKEY = Internal.createUniqueKey(RolePermission.ROLE_PERMISSION, "role_permission_pkey", RolePermission.ROLE_PERMISSION.ROLE, RolePermission.ROLE_PERMISSION.PERMISSION);
        public static final UniqueKey<UserGroupRecord> USER_GROUP_PKEY = Internal.createUniqueKey(UserGroup.USER_GROUP, "user_group_pkey", UserGroup.USER_GROUP.ID);
        public static final UniqueKey<UserGroupMembershipRecord> USER_GROUP_MEMBERSHIP_PKEY = Internal.createUniqueKey(UserGroupMembership.USER_GROUP_MEMBERSHIP, "user_group_membership_pkey", UserGroupMembership.USER_GROUP_MEMBERSHIP.USERNAME, UserGroupMembership.USER_GROUP_MEMBERSHIP.USER_GROUP);
        public static final UniqueKey<UserGroupRoleRecord> USER_GROUP_ROLE_PKEY = Internal.createUniqueKey(UserGroupRole.USER_GROUP_ROLE, "user_group_role_pkey", UserGroupRole.USER_GROUP_ROLE.USER_GROUP, UserGroupRole.USER_GROUP_ROLE.ROLE, UserGroupRole.USER_GROUP_ROLE.SCOPE_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<UserGroupMembershipRecord, AppUserRecord> USER_GROUP_MEMBERSHIP__USER_GROUP_MEMBERSHIP_USERNAME_FKEY = Internal.createForeignKey(org.mrc.ide.auth.db.Keys.APP_USER_PKEY, UserGroupMembership.USER_GROUP_MEMBERSHIP, "user_group_membership__user_group_membership_username_fkey", UserGroupMembership.USER_GROUP_MEMBERSHIP.USERNAME);
        public static final ForeignKey<UserGroupMembershipRecord, UserGroupRecord> USER_GROUP_MEMBERSHIP__USER_GROUP_MEMBERSHIP_USER_GROUP_FKEY = Internal.createForeignKey(org.mrc.ide.auth.db.Keys.USER_GROUP_PKEY, UserGroupMembership.USER_GROUP_MEMBERSHIP, "user_group_membership__user_group_membership_user_group_fkey", UserGroupMembership.USER_GROUP_MEMBERSHIP.USER_GROUP);
        public static final ForeignKey<UserGroupRoleRecord, UserGroupRecord> USER_GROUP_ROLE__USER_GROUP_ROLE_USER_GROUP_FKEY = Internal.createForeignKey(org.mrc.ide.auth.db.Keys.USER_GROUP_PKEY, UserGroupRole.USER_GROUP_ROLE, "user_group_role__user_group_role_user_group_fkey", UserGroupRole.USER_GROUP_ROLE.USER_GROUP);
        public static final ForeignKey<UserGroupRoleRecord, RoleRecord> USER_GROUP_ROLE__USER_GROUP_ROLE_ROLE_FKEY = Internal.createForeignKey(org.mrc.ide.auth.db.Keys.ROLE_PKEY, UserGroupRole.USER_GROUP_ROLE, "user_group_role__user_group_role_role_fkey", UserGroupRole.USER_GROUP_ROLE.ROLE);
    }
}
